services:
  sqlserverMedilabo:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserverMedilabo
    environment:  
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Medilabo2026!"
    ports:
      - "1433:1433" 
    volumes:
      - sqlserver_data:/var/opt/mssql 
    networks:
      - medilabo-network
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Medilabo2026!", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 5

  apigatewaymedilabo:
    image: apigatewaymedilabo
    ports:
      - "32768:8080"
    build: "./APIGatewayMediLabo/"
    networks:
      - medilabo-network
   
  mongodb:
    image: mongo:8
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - medilabo-network

  apiauthenticationmedilabo:
    image: apiauthenticationmedilabo
    ports:
      - "32771:8080"
    depends_on:
      apigatewaymedilabo:
        condition: service_started
      sqlserverMedilabo:
        condition: service_healthy
    build: "./APIAuthenticationMedilabo/"
    networks:
      - medilabo-network

  apiinformationspatient:
    image: apiinformationspatient
    ports:
      - "32769:8080"
    depends_on:
      apigatewaymedilabo:
        condition: service_started
      apiauthenticationmedilabo:
        condition: service_started
      sqlserverMedilabo:
        condition: service_healthy
    build: "./APIInformationsPatient/"
    networks:
      - medilabo-network

  frontpatient:
    image: frontpatient
    ports:
      - "32770:8080"
    depends_on:
      - apigatewaymedilabo
      - apiinformationspatient
      - apinoteshistopatientsmedilabo
    build: "./FrontPatient/"
    networks:
      - medilabo-network

  apinoteshistopatientsmedilabo:
    image: apinoteshistopatientsmedilabo
    ports:
      - "32772:8080"
    depends_on:
      - apigatewaymedilabo
      - apiauthenticationmedilabo 
      - mongodb
    build: "./APINotesHistoPatientsMedilabo/"
    networks:
      - medilabo-network

  apirapportpatient:
    image: apirapportpatient
    ports:
      - "32773:80"
    depends_on:
      - apigatewaymedilabo
      - apiauthenticationmedilabo 
    build: "./APIRapportPatient/"
    networks:
      - medilabo-network

volumes:
  mongodb_data:  
  sqlserver_data:  

networks:
  medilabo-network:
    driver: bridge      
  